### ISSUE TITLE
django-realtime can not be installed with pip

### ISSUE THREAD

**Issue by tomikall** [jstasiak/django-realtime#1]
Two problems with setup.py:
1. It imports the `realtime` package, creating a install time dependency to Django (imports `django.dispatch`). Even after Django is installed, installation fails unless DJANGO_SETTINGS_MODULE is defined and the module it points to is available. This means your package can not be installed unless you already have a properly configured, working Django installation.

I suggest not importing the package but reading in `realtime/__init__.py` as text and finding the version information with a regular expression or with simple string splitting:

``` python
open(os.path.join(os.path.dirname(__file__),
                                 "realtime", "__init__.py")).readline().split()[-1].strip("'")
```
1. Long description is read from `README.md` which (no longer?) exists.

Fix for this one is trivial (`.md` -> `.rst`).

**Comment by jstasiak** [comment]
You are absolutely right, `README.md` no longer exists. I also changed version detection, fixed in 63a61a852d7.

Thank you for your input :)

**Comment by tomikall** [comment]
Great, thanks!

I just noticed that the versiontools package provides a convenient way to extract the version information:

http://packages.python.org/versiontools/usage.html#adding-support-for-your-project

**Comment by jstasiak** [comment]
I see, it is nice, but doesn't it just internally import module, which in this case would result in problem described by you in the first place?

**Comment by tomikall** [comment]
So it seems -- sorry, I did not even look at the source. It is also licensed under GPL, so perhaps not such a great companion to your BSD licensed project.

**Comment by jstasiak** [comment]
Yeah, re-based extraction has to do for now ;)

**Comment by neokeats** [comment]
hi, 

```
pip install git+https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e@
```

doesn't work, it returns : 

Downloading/unpacking git+https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e@
  Cloning https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e to /tmp/pip-7bJIP9-build
fatal: https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e/info/refs not found: did you run git update-server-info on the server?
  Complete output from command /usr/bin/git clone -q https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e /tmp/pip-7bJIP9-build:

---

Command /usr/bin/git clone -q https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e /tmp/pip-7bJIP9-build failed with error code 128 in None
Storing complete log in /root/.pip/pip.log

**Comment by jstasiak** [comment]
Hey, sorry for the delay. It seems that you have an extra @ at the end of the command line. If you enter it like

```
pip install git+https://jstasiak@github.com/jstasiak/gevent-socketio.git@8835a91dffba4447564ffa30df95663a13e1997e
```

it should work as it supposed to do.
