### ISSUE TITLE
Socket AttributeError

### ISSUE THREAD

**Issue by aleg** [jstasiak/django-realtime#2]
Hi,
I'm trying to use django-realtime with the chat example. When I insert the user name, the following error is raised (from every signal, but the first is the `socket_client_event_by_type['chat_set_name']` signal):

This is the error:

``` python
AttributeError: 'Socket' object has no attribute 'session'
<Greenlet at 0xa6ee7fc: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0xa6db80c>>> failed with AttributeError
```

This is my virtualenv:

``` bash
Django==1.4.3
anyjson==0.3.3
argparse==1.2.1
django-realtime==0.1.1
gevent==0.13.8
gevent-socketio==0.3
gevent-websocket==0.3.6
greenlet==0.4.0
wsgiref==0.1.2
```

**Comment by jstasiak** [comment]
Hi, thanks for the note and sorry about the delay with my response. Commit bf7a90d should fix that for you (note - it requires most recent official gevent-socketio, not my fork anymore, and involves some really nasty hackery to make it compatible with newest gevent-socketio).

That said, I don't believe my project is reasonable and needed anymore, not in this form anyway. If you want to develop with Django and gevent-socketio I suggest you just use Django-related stuff from https://github.com/abourget/gevent-socketio.
